## Numpy:Package for Multidimensional array

In [7]:
import numpy as np

In [22]:
simple_list=[3,6,9]
np.array(simple_list)

array([3, 6, 9])

In [8]:
arr =np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
list_of_lists=([2,3,4],[6,7,8],[1,7,9])
np.array(list_of_lists)

array([[2, 3, 4],
       [6, 7, 8],
       [1, 7, 9]])

In [11]:
np.arange(1,59)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58])

In [18]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [14]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(3,5)

array([[0.9500573 , 0.80762552, 0.53403549, 0.13345768, 0.14559216],
       [0.23038806, 0.55307959, 0.56022868, 0.65883198, 0.03586515],
       [0.26969032, 0.17273838, 0.6503566 , 0.24172264, 0.18402539]])

In [15]:
arr =np.random.randn(2,4)
arr

array([[-1.12936444,  0.05933554,  0.60447041,  0.473266  ],
       [ 0.22391023, -0.03159682,  0.11852371, -1.65889456]])

In [17]:
np.random.randint(20,56,100)

array([21, 47, 27, 20, 28, 27, 40, 37, 30, 47, 32, 22, 44, 48, 41, 21, 34,
       53, 36, 28, 28, 51, 22, 54, 46, 31, 36, 42, 20, 20, 34, 47, 51, 26,
       51, 24, 30, 28, 46, 30, 26, 47, 44, 37, 28, 42, 53, 51, 22, 32, 20,
       30, 44, 27, 51, 43, 40, 33, 54, 42, 35, 26, 53, 23, 28, 31, 39, 20,
       39, 51, 34, 31, 31, 49, 31, 53, 33, 26, 34, 34, 46, 53, 42, 47, 39,
       49, 53, 27, 46, 33, 44, 42, 21, 43, 47, 55, 34, 33, 38, 37])

In [3]:
sample_array=np.arange(30)

In [4]:
sample_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
sample_array.reshape(5,9)

ValueError: cannot reshape array of size 30 into shape (5,9)

In [27]:
rand_array =np.random.randint(0,100,20)
rand_array

array([20, 57,  9, 14, 91, 99, 54, 52, 31, 16, 69, 62, 54, 90, 95, 59, 34,
       66,  1, 33])

In [28]:
sample_array.reshape(5,9)

ValueError: cannot reshape array of size 30 into shape (5,9)

In [29]:
rand_array.min()

1

In [30]:
rand_array.argmax()

5

In [32]:
a=np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
a.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [34]:
a =np.random.rand(2,3)
a

array([[0.0743321 , 0.25963178, 0.95301827],
       [0.6252762 , 0.64043401, 0.69734222]])

In [50]:
a.T

array([[0.0743321 , 0.6252762 ],
       [0.25963178, 0.64043401],
       [0.95301827, 0.69734222]])

In [36]:
sample_array=np.arange(11,22)

In [37]:
sample_array[9]

20

In [39]:
sample_array[0:9]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
sample_array[1:7]

array([12, 13, 14, 15, 16, 17])

In [47]:
subset_sample_array =sample_array[0:7]
subset_sample_array

array([11, 12, 13, 14, 15, 16, 17])

In [49]:
subset_sample_array[:] =72
subset_sample_array

array([72, 72, 72, 72, 72, 72, 72])

## Two-dimensional array

In [51]:
import numpy as np

In [55]:
sample_matrix =np.array(([23,4,6],[67,43,2],[76,47,34]))
sample_matrix

array([[23,  4,  6],
       [67, 43,  2],
       [76, 47, 34]])

In [56]:
sample_matrix[1,2]

2

In [57]:
sample_matrix[2,:]

array([76, 47, 34])

In [58]:
sample_matrix[2]

array([76, 47, 34])

In [67]:
sample_matrix[:,(1,2)]

array([[ 4,  6],
       [43,  2],
       [47, 34]])

In [68]:
sample_array =np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [69]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [70]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [73]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [74]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [75]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [76]:
np.max(sample_array)

19

In [77]:
np.min(sample_array)

1

In [78]:
np.argmax(sample_array)

18

In [71]:
np.argmin(sample_array)


0

In [72]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [79]:
np.std(sample_array)


5.477225575051661

In [80]:
np.var(sample_array)

30.0

In [81]:
np.mean(sample_array)


10.0

In [82]:
array =np.random.randn(3,4)
array

array([[-0.83057058,  0.85000653,  0.30148015,  0.49111616],
       [-0.7564919 ,  0.85143991,  2.52419354, -1.42008861],
       [ 0.76930329, -2.1931948 , -0.05053334,  1.35266924]])

In [83]:
np.round(array,decimals=2)

array([[-0.83,  0.85,  0.3 ,  0.49],
       [-0.76,  0.85,  2.52, -1.42],
       [ 0.77, -2.19, -0.05,  1.35]])

In [85]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

### Pandas

In [2]:
import pandas as pd


In [3]:
pd.Series(["A","B","C","D","E"])

0    A
1    B
2    C
3    D
4    E
dtype: object

In [4]:
import numpy as np


In [5]:
gen=pd.Series(np.array(["W","X","Y","Z"]))

In [6]:
type(gen)

pandas.core.series.Series

In [7]:
dic={"A":56,"B":12,32:8,93:"R"}
dic_1=pd.Series(dic)

In [8]:
pd.Series(dic)

A     56
B     12
32     8
93     R
dtype: object

In [9]:
type(dic_1)

pandas.core.series.Series

In [10]:
type(dic)

dict

In [11]:
dic_1.index

Index(['A', 'B', 32, 93], dtype='object')

In [12]:
dic_1.values

array([56, 12, 8, 'R'], dtype=object)

In [13]:
list_1=["2023-04-16" ,17.2,"komal",True]

In [14]:
ser=pd.Series(list_1)

In [15]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [16]:
df=pd.DataFrame({"Name":["panda","romeo","komal"],"Age":[21,22,23],
             "Sex":["Female","Male","Female"]})

In [17]:
type(df["Age"])

pandas.core.series.Series

In [18]:
df["Age"]

0    21
1    22
2    23
Name: Age, dtype: int64

In [19]:
df["Age"][0]

21

In [20]:
df["Name"][2]

'komal'

In [21]:
df.columns

Index(['Name', 'Age', 'Sex'], dtype='object')

In [22]:
ser1=pd.Series([0,1,2,3,4],index=[0,1,2,7,6])
ser2=pd.Series([0,1,2,3,4],index=[1,2,3,4,5])


In [23]:
ser1

0    0
1    1
2    2
7    3
6    4
dtype: int64

In [24]:
ser2

1    0
2    1
3    2
4    3
5    4
dtype: int64

In [25]:
ser1+ser2

0    NaN
1    1.0
2    3.0
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
dtype: float64

In [26]:
ser1=pd.Series(["Apple","Lichi","Berry","Grapes"],index=[0,1,2,7])
ser2=pd.Series(["Apple","Lichi","Berry","Grapes"],index=[2,3,4,5])

In [27]:
ser1

0     Apple
1     Lichi
2     Berry
7    Grapes
dtype: object

In [28]:
ser2

2     Apple
3     Lichi
4     Berry
5    Grapes
dtype: object

In [29]:
ser1+ser2

0           NaN
1           NaN
2    BerryApple
3           NaN
4           NaN
5           NaN
7           NaN
dtype: object

In [35]:
ser1=pd.Series([0,1,2,7],index=["Apple","Lichi","Berry","Grapes"])
ser2=pd.Series([2,3,4,5],index=["Apple","Lichi","Berry","Grapes"])

In [36]:
ser1

Apple     0
Lichi     1
Berry     2
Grapes    7
dtype: int64

In [37]:
ser2

Apple     2
Lichi     3
Berry     4
Grapes    5
dtype: int64

In [38]:
ser1+ser2

Apple      2
Lichi      4
Berry      6
Grapes    12
dtype: int64

In [39]:
ser1.sum()

10

In [40]:
ser2.sum()

14

In [41]:
ser2+ser1

Apple      2
Lichi      4
Berry      6
Grapes    12
dtype: int64

In [42]:
ser1.median()

1.5

In [43]:
ser1.min()

0

In [44]:
ser2.max()

5

In [45]:
ser1.std()

3.1091263510296048

In [46]:
ser2.std()

1.2909944487358056

In [47]:
ser1.sort_values()

Apple     0
Lichi     1
Berry     2
Grapes    7
dtype: int64

In [49]:
 ser3=pd.Series([17,18,19],name="rollno")
    

In [58]:
plus_10=lambda x:x+10


In [59]:
plus_10(7)


17

In [60]:
ser3.apply(lambda x:x+10)

0    27
1    28
2    29
Name: rollno, dtype: int64

In [61]:
ser3.apply(lambda x:x*10)

0    170
1    180
2    190
Name: rollno, dtype: int64